### PR TITLE
Ingesting spectra for Manj16

### PR DESCRIPTION
**Pull request by SherelynA**

### CODE REVIEW

**Comment by kelle** [comment]
Xshooter has only one mode so providing a mode isn't necessary.

**Comment by SherelynA** [comment]
Everything seems to looks good and ready to merge

**Comment by kelle** [comment]
This looks great!  Only thing which we should do is to add a new data test for the `em.IR.NIR` and `em.opt` regimes. 

On lines 243-249 of `test_data.py` there are tests for `nir` and `optical`. Can you use those a guide to add two new tests for  `em.IR.NIR` and `em.opt` regimes?

**Review by kelle — CHANGES_REQUESTED** [review]
This looks great!  Only thing which we should do is to add a new data test for the `em.IR.NIR` and `em.opt` regimes. 

On lines 243-249 of `test_data.py` there are tests for `nir` and `optical`. Can you use those a guide to add two new tests for  `em.IR.NIR` and `em.opt` regimes?

**Comment by SherelynA** [comment]
> This looks great! Only thing which we should do is to add a new data test for the `em.IR.NIR` and `em.opt` regimes.
> 
> On lines 243-249 of `test_data.py` there are tests for `nir` and `optical`. Can you use those a guide to add two new tests for `em.IR.NIR` and `em.opt` regimes?

I added the two new test that check for those two regimes.

**Review by kelle — APPROVED** [review]

**Comment by kelle** [comment]
This looks perfect -- great work!

**Pull request merged**
