### PR TITLE
Rename spectrum to access_url

### LINKED ISSUE #477: Change `spectrum` to `access_url` in the Spectrum table.
Consolidated from https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/353.

Change `spectrum` to `access_url` in the Spectrum table.

### PR DESCRIPTION
**Pull request by dr-rodriguez**
Short description:   
Rename the `spectrum` column to `access_url` in the _Spectra_ table

Link to relevant issue: Closes #477 

For data ingests:
[X] includes script used for ingest
[X] includes modified JSON files
[X] Add/update tests
[X] Update the Versions table

### CODE REVIEW

**Comment by dr-rodriguez** [comment]
Do we want/need an entry in _Versions_ as described in the template?

**Review by kelle — CHANGES_REQUESTED** [review]
Please also update `test/scheduled_checks.py`

**Comment by kelle** [comment]
> Also, I did notice the re-ordering of a handful of _SpectralTypes_ entries. Not sure how to resolve that yet, but maybe this PR will sync them to their proper order?

I'm happy to do that here since so many files are being touched anyway.  If it happens again, however, we should open an issue and see if we can prescribe the order.

**Comment by kelle** [comment]
> Do we want/need an entry in _Versions_ as described in the template?

I vote yes, I think this change warrants a release and a version increment.  We'll need to be careful implementing on the website because this change may break the web app.

**Comment by dr-rodriguez** [comment]
Updated scheduled_checks and added an entry to Versions (2024.4). 
These are now the versions we have:
```
version start_date  end_date                    description                  
------- ---------- ---------- -----------------------------------------------
 2022.1 2020-06-22 2022-08-23                                 Initial release
 2022.2 2022-08-23 2022-10-11                                            None
 2022.3 2022-10-11 2022-10-13                            Added VHS 1256b data
 2022.4 2022-10-14 2022-10-16                                                
 2022.5 2022-10-16 2022-12-28 Adds T and Y dwarfs from Leggett 21 compilation
 2023.1 2022-12-28 2023-07-11                                   Schema rework
 2023.2 2023-07-11 2023-07-25                Added JWST spectra for VHS 1256b
 2023.3 2023-07-25 2023-10-18             Companions table, fixed IRS spectra
 2023.4 2023-10-18 2023-12-12                               Added two sources
 2023.5 2023-12-12 2023-12-29     Included Roth sources, fixed Bard14 spectra
 2024.1 2023-12-29 2024-02-15          Added JWST spectrum for WISE 1935-1546
 2024.2 2024-02-15 2024-03-05                                  Regime cleanup
 2024.3 2024-03-05 2024-04-17                 UCDs in PhotometryFilters table
 2024.4 2024-04-17 2024-04-19 Renaming Spectra.spectrum to Spectra.access_url
 latest 2024-04-19       None                          Version in development
```

**Review by kelle — APPROVED** [review]
Looks great!

**Pull request merged**
