### PR TITLE
Suárez Ingest 2022

### PR DESCRIPTION
**Pull request by SherelynA**
Started the Suarez Ingest

### CODE REVIEW

**Comment by SherelynA** [comment]
Link to google sheet: https://docs.google.com/spreadsheets/d/1ojsNF59GvdFhf-lgwJaCwiHPfaRx4fmCpyzKEonrVbw/edit?usp=sharing

**Comment by kelle** [comment]
Do you have the converted fits files Jolie made? We should add those now too. Put the .dat files in original but the new .fits as the spectrum. (Actually, I think I have them...gimme a couple minutes.)

**Comment by kelle** [comment]
I uploaded the converted fits files. They have paths like this: https://bdnyc.s3.amazonaws.com/IRS/0000%252B2554_IRS_spectrum.fits.  Here are all the files I uploaded so you know their names.
[Suarez2022.zip](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9305207/Suarez2022.zip)

**Comment by SherelynA** [comment]
@kelle I just saw your comments, do I just change the script  to include the .dat in original and the rest in the spectrum column and then recreate the json files or do I have to delete the current json files I made?

**Comment by kelle** [comment]
I think you can rewrite the script as you suggest. Once you do Save_db it will re-write the JSON file. You don't have to delete them. But you will have to re-commit and push them.

**Comment by kelle** [comment]
Decided to start over! in #278

**Pull request closed without merging**
