### PR TITLE
Adding notes to documentation and indicating required fields.

### PR DESCRIPTION
**Pull request by kelle**
Added * to required field names and some notes and links on the documentation for most of the tables.

### CODE REVIEW

**Comment by kelle** [comment]
I can't quite figure out why the tests are failing on this....the changes I made are only to the docs.

**Comment by dr-rodriguez** [comment]
Looks like github actions have been having issues today and for a while on our tests. I ran this branch locally today and had no issues.

**Comment by dr-rodriguez** [comment]
I think we should explicitly specify somewhere that * represents a required field (maybe it's specified already and I didn't see it?). 
From the column descriptions alone it looks like it could either mean **required** or **unique** and those are two separate concepts.

**Review by dr-rodriguez — APPROVED** [review]
Looks good

**Pull request merged**
